### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by RobertGalatNordic** [deepakpahwa19/flow-bookmarks#10]
In file README.md there are broken links:
demo -> https://github.com/deepakpahwa19/flow-bookmarks/blob/master/images/bookmark-vscode.png?raw=true
AddBookmark -> https://github.com/deepakpahwa19/flow-bookmarks/blob/master/images/FB-AddBookmark-min.gif?raw=true
EditBookmark -> https://github.com/deepakpahwa19/flow-bookmarks/blob/master/images/Edit-Bookmark-Flow-min.gif?raw=true

**Comment by deepakpahwa19** [comment]
Thanks for raising the bug. I will update those. 

Please check the README.md in marketplace as that has the actual link.
https://marketplace.visualstudio.com/items?itemName=DeepakPahawa.flowbookmark&ssr=false#review-details
