### ISSUE TITLE
Bookmark line postion does not get updated if newlines are entered

### ISSUE THREAD

**Issue by fade2gray** [deepakpahwa19/flow-bookmarks#2]
Hi,

I really like this extension but it has one major problem...

If newlines are entered before a bookmark position, the bookmark line does not get updated.

e.g if there is a bookmark at line 3 and a newline is inserted before line 3, the bookmark should be moved to line 4.

![1](https://user-images.githubusercontent.com/1332009/92326484-910cc200-f04a-11ea-9570-3e6ffefec173.PNG)
![2](https://user-images.githubusercontent.com/1332009/92326488-966a0c80-f04a-11ea-872b-648c1eba9d8d.PNG)

**Comment by deepakpahwa19** [comment]
I am glad you liked it and Thank you for the feedback.

I will work on it and solve it.

**Comment by deepakpahwa19** [comment]
It was a big flaw in the bookmark which has been fixed with v2.0.2

Thanks a lot for creating an issue. Have mentioned your name in the README for the same. Thanks
