### ISSUE TITLE
[Feature Request] Default to last used Flow name

### ISSUE THREAD

**Issue by bluprince13** [deepakpahwa19/flow-bookmarks#4]
**Current behaviour**

Typically, the user is adding bookmarks to the same flow. However, they have to specify the flow each time they create a bookmark.

When creating a bookmark if the user only specifies a bookmark name, but not a flow name, then flow name is set to `Uncategorised`.

**Desired behaviour**

The flow name defaults to the last flow name added to by the user in the current session. If the user is adding a bookmark for the first time in this session, then flow name is set to `Uncategorised`.

**Comment by deepakpahwa19** [comment]
@bluprince13 It can be a minor change, I'll make it soon. Thanks

**Comment by deepakpahwa19** [comment]
It is fixed with v2.0.2. Please update the plugin

A big thank you for the small but convenient feature. Thanks a lot.

**Comment by bluprince13** [comment]
Brill. Tried it out and it's great. Thanks!
