### ISSUE TITLE
[Feature Request] Ability to rename/delete a flow

### ISSUE THREAD

**Issue by bluprince13** [deepakpahwa19/flow-bookmarks#5]
**Current behaviour**

- To rename a flow, the user has to rename the flow individually for each bookmark in that flow.
- To delete a flow, the user has to delete each bookmark in that flow.

**Desired behaviour**

Rename/delete a flow with a single action by the user. The UI could show a edit/delete option next to the flow name on hover.

**Comment by deepakpahwa19** [comment]
@bluprince13 That will be a good enhancement. I will work on it after the new feature I am implementing

Thank you so much for the request.

**Comment by bluprince13** [comment]
Thank you. This is such an awesome extension. 🙂

Do you accept pull requests btw? If so, is the correct repo deepakpahwa19/flow-bookmark? I was a bit confused.

**Comment by deepakpahwa19** [comment]
Currently, I've not made it open source. Yeah but in future, I will do that for sure.

Please recommend to your friends to use it.

**Comment by deepakpahwa19** [comment]
I have added the functionality to edit the flow name. To prevent deleting a flow accidentally, I am not adding that feature.

Thank you for the suggestion.
